# version: '3.8'

services:
  scientists-database-services:
    build: 
      context: . 
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - .venv:/app/.venv 
    ports:
      - "5000:5000" 
    env_file:
      - .env
    container_name: flask_container
    networks:
      - scientists
    depends_on:
      - scientists-postgres-db
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
      DATABASE_URL: ${DATABASE_URL}

  scientists-postgres-db:
    build: 
        context: config_db
        dockerfile: Dockerfile
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5435:5432"
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - scientists

  test-runner:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: pytest --disable-warnings
    volumes:
      - .:/app
    env_file:
      - .env
    networks:
      - scientists
    depends_on:
      - scientists-database-services
      - scientists-postgres-db
    

volumes:
  postgres_data:
    name: postgres_data

networks:
  scientists:
    name: scientists
    driver: bridge
