# Use the official Python image
FROM python:3.12-slim

# Install the necessary system dependencies
RUN apt-get update && apt-get install -y libpq-dev gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Set the working directory to /app
WORKDIR /app

# Copy configuration files of poetry
COPY pyproject.toml poetry.lock* /app/

# Install poetry
RUN pip install poetry && \
    poetry config virtualenvs.create false

# Install dependencies
RUN poetry install --no-root

# Copy the application code to the container
COPY . /app

# Expose the port 5000 for the application
EXPOSE 5000

# Command to run the application
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "run:app"]


