# Usa la imagen base de Python
FROM python:3.12-slim

# Instalar dependencias del sistema necesarias
RUN apt-get update && apt-get install -y libpq-dev gcc && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar archivos de configuración de Poetry
COPY pyproject.toml poetry.lock* /app/

# Instalar Poetry
RUN pip install poetry && \
    poetry config virtualenvs.create false

# Instalar las dependencias directamente en el sistema del contenedor
RUN poetry install --no-root

# Copiar el resto de la aplicación
COPY ./ /app

# Exponer el puerto de la aplicación
EXPOSE 5000

# Comando predeterminado para ejecutar la aplicación con uvicorn
CMD ["gunicorn", "-w", "4", "-b", "0.0.0.0:5000", "run:app"]


